version: '3.7'

services:
  redis:
   image: redis:7.4-alpine
   container_name: rick-morty-redis
   restart: always
   ports:
    - '6379:6379'
   command: redis-server --loglevel warning --requirepass password123